apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: soma-platform
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_PASSWORD
          value: catsarecool
        - name: PGADMIN_DEFAULT_EMAIL
          value: user@domain.com
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: soma-platform
  labels:
    app: pgadmin
spec:
  type: LoadBalancer
  ports:
  - port: 5050
    targetPort: 80
    protocol: TCP
  selector:
    app: pgadmin